/* LANDING PAGE COMPONENT */
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Shield, ShieldCheck, Twitter, Github, Linkedin, X, FileText, Lock, Globe, Send, Mail, Facebook, Youtube, CheckCircle2, Loader2 } from "lucide-react";
import type { LucideProps } from "lucide-react";
import Link from "next/link";
import { useState, useEffect, useRef } from "react";
import { Turnstile, type TurnstileInstance } from "@marsidev/react-turnstile";

const footerLinks = {
  Platform: [
    { label: "Dashboard", href: "/dashboard" },
    { label: "product", href: "/product" },
    { label: "Admin", href: "/admin" },
  ],
  Explore: [
    { label: "Workflow", href: "/#workflow" },
    { label: "Architecture", href: "/#architecture" },
    { label: "Pricing", href: "/#pricing" }
  ],
  Legal: [
    { label: "Privacy Policy", slug: "privacy" },
    { label: "Terms and Condition", slug: "terms" },
    { label: "Cookies", slug: "cookies" },
  ],
};

function PinterestIcon(props: LucideProps) {
  const { className, ...rest } = props;
  return (
    <svg
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      className={className}
      {...rest}
    >
      <path d="M12.017 0C5.396 0 0 5.397 0 12.017c0 5.078 3.158 9.412 7.618 11.169-.103-.949-.19-2.405.04-3.436.205-.874 1.325-5.62 1.325-5.62s-.331-.663-.331-1.644c0-1.54.896-2.69 2.01-2.69.948 0 1.405.711 1.405 1.564 0 .953-.607 2.379-.92 3.702-.262 1.107.558 2.01 1.65 2.01 1.981 0 3.5-2.09 3.5-5.109 0-2.671-1.92-4.538-4.66-4.538-3.174 0-5.037 2.381-5.037 4.842 0 .959.369 1.987.828 2.543.09.11.103.207.076.317l-.307 1.258c-.049.202-.162.245-.373.147-1.391-.647-2.261-2.678-2.261-4.31 0-3.51 2.55-6.733 7.351-6.733 3.859 0 6.858 2.751 6.858 6.427 0 3.834-2.417 6.921-5.77 6.921-1.127 0-2.186-.585-2.548-1.275 0 0-.557 2.122-.693 2.642-.25.962-.924 2.169-1.375 2.9.957.28 1.968.43 3.014.43 6.62 0 12.017-5.397 12.017-12.017S18.636 0 12.017 0z" />
    </svg>
  );
}

const LEGAL_CONTENT = {
  privacy: {
    title: "Privacy Policy",
    icon: Lock,
    lastUpdated: "March 18, 2026",
    content: `
<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h3>Definitions</h3>
<p>For the purposes of this Privacy Policy:</p>
<ul>
<li>
<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
</li>
<li>
<p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Tekverai.com, 28 Geary St, Suite 650, San Francisco, CA 94108, United States .</p>
</li>
<li>
<p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
</li>
<li>
<p><strong>Country</strong> refers to: California,  United States</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
</li>
<li>
<p><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</p>
<p>We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Website.</p>
</li>
<li>
<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
</li>
<li>
<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
</li>
<li>
<p><strong>Website</strong> refers to Tekverai.com, accessible from <a href="http://tekverai.com/" rel="external nofollow noopener" target="_blank">http://tekverai.com/</a>.</p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<h2>Collecting and Using Your Personal Data</h2>
<h3>Types of Data Collected</h3>
<h4>Personal Data</h4>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
<ul>
<li>Email address</li>
<li>First name and last name</li>
</ul>
<h4>Usage Data</h4>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
<h4>Tracking Technologies and Cookies</h4>
<p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
<ul>
<li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
<li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
</ul>
<p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
<p>Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
<p>We use both Session and Persistent Cookies for the purposes set out below:</p>
<ul>
<li>
<p><strong>Necessary / Essential Cookies</strong></p>
<p>Type: Session Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
</li>
<li>
<p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
</li>
<li>
<p><strong>Functionality Cookies</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
</li>
</ul>
<p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of Our Privacy Policy.</p>
<h3>Use of Your Personal Data</h3>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
<li>
<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
</li>
<li>
<p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
</li>
<li>
<p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
</li>
<li>
<p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
</li>
<li>
<p><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</p>
</li>
<li>
<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
</li>
<li>
<p><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
</li>
<li>
<p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
</li>
</ul>
<p>We may share Your Personal Data in the following situations:</p>
<ul>
<li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>
<li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
<li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
<li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
<li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
<li><strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
</ul>
<h3>Retention of Your Personal Data</h3>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&quot;up to&quot;) and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
<ul>
<li>
<p>Account Information</p>
<ul>
<li>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.</li>
</ul>
</li>
<li>
<p>Customer Support Data</p>
<ul>
<li>Support tickets and correspondence: up to 24 months from the date of ticket closure to resolve follow-up inquiries, track service quality, and defend against potential legal claims</li>
<li>Chat transcripts: up to 24 months for quality assurance and staff training purposes.</li>
</ul>
</li>
<li>
<p>Usage Data</p>
<ul>
<li>
<p>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection, which allows us to analyze trends while respecting privacy principles.</p>
</li>
<li>
<p>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</p>
</li>
</ul>
</li>
</ul>
<p>Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.</p>
<p>We may retain Personal Data beyond the periods stated above for different reasons:</p>
<ul>
<li>Legal obligation: We are required by law to retain specific data (e.g., financial records for tax authorities).</li>
<li>Legal claims: Data is necessary to establish, exercise, or defend legal claims.</li>
<li>Your explicit request: You ask Us to retain specific information.</li>
<li>Technical limitations: Data exists in backup systems that are scheduled for routine deletion.</li>
</ul>
<p>You may request information about how long We will retain Your Personal Data by contacting Us.</p>
<p>When retention periods expire, We securely delete or anonymize Personal Data according to the following procedures:</p>
<ul>
<li>Deletion: Personal Data is removed from Our systems and no longer actively processed.</li>
<li>Backup retention: Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule and are not restored except where necessary for security, disaster recovery, or legal compliance.</li>
<li>Anonymization: In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You. This anonymized data may be retained indefinitely for research and analytics.</li>
</ul>
<h3>Transfer of Your Personal Data</h3>
<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
<p>Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
<h3>Delete Your Personal Data</h3>
<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
<p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
<p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
<p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
<h3>Disclosure of Your Personal Data</h3>
<h4>Business Transactions</h4>
<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<h4>Law enforcement</h4>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
<h4>Other legal requirements</h4>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
<li>Comply with a legal obligation</li>
<li>Protect and defend the rights or property of the Company</li>
<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
<li>Protect the personal safety of Users of the Service or the public</li>
<li>Protect against legal liability</li>
</ul>
<h3>Security of Your Personal Data</h3>
<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
<h2>Links to Other Websites</h2>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<h2>Changes to this Privacy Policy</h2>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
<li>
<p>By email: connect@tekverai.com</p>
</li>
<li>
<p>By phone: +12246589300</p>
</li>
</ul>
    `
  },
  terms: {
    title: "Terms and Condition",
    icon: FileText,
    lastUpdated: "March 18, 2026",
    content: `
<p>Please read these terms and conditions carefully before using Our Service.</p>
<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h3>Definitions</h3>
<p>For the purposes of these Terms and Conditions:</p>
<ul>
<li>
<p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
</li>
<li>
<p><strong>Country</strong> refers to: California,  United States</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in these Terms and Conditions) refers to Tekverai.com, 28 Geary St, Suite 650, San Francisco, CA 94108, United States .</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Website.</p>
</li>
<li>
<p><strong>Terms and Conditions</strong> (also referred to as &quot;Terms&quot;) means these Terms and Conditions, including any documents expressly incorporated by reference, which govern Your access to and use of the Service and form the entire agreement between You and the Company regarding the Service.</p>
</li>
<li>
<p><strong>Third-Party Social Media Service</strong> means any services or content (including data, information, products or services) provided by a third party that is displayed, included, made available, or linked to through the Service.</p>
</li>
<li>
<p><strong>Website</strong> refers to Tekverai.com, accessible from <a href="http://tekverai.com/" rel="external nofollow noopener" target="_blank">http://tekverai.com/</a></p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<h2>Acknowledgment</h2>
<p>These are the Terms and Conditions governing the use of this Service and the agreement between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
<p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
<p>By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.</p>
<p>You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
<p>Your access to and use of the Service is also subject to Our Privacy Policy, which describes how We collect, use, and disclose personal information. Please read Our Privacy Policy carefully before using Our Service.</p>
<h2>Links to Other Websites</h2>
<p>Our Service may contain links to third-party websites or services that are not owned or controlled by the Company.</p>
<p>The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such websites or services.</p>
<p>We strongly advise You to read the terms and conditions and privacy policies of any third-party websites or services that You visit.</p>
<h3>Links from a Third-Party Social Media Service</h3>
<p>The Service may display, include, make available, or link to content or services provided by a Third-Party Social Media Service. A Third-Party Social Media Service is not owned or controlled by the Company, and the Company does not endorse or assume responsibility for any Third-Party Social Media Service.</p>
<p>You acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with Your access to or use of any Third-Party Social Media Service, including any content, goods, or services made available through them. Your use of any Third-Party Social Media Service is governed by that Third-Party Social Media Service's terms and privacy policies.</p>
<h2>Termination</h2>
<p>We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.</p>
<p>Upon termination, Your right to use the Service will cease immediately.</p>
<h2>Limitation of Liability</h2>
<p>Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of these Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You through the Service or 100 USD if You haven't purchased anything through the Service.</p>
<p>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of these Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
<p>Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party's liability will be limited to the greatest extent permitted by law.</p>
<h2>&quot;AS IS&quot; and &quot;AS AVAILABLE&quot; Disclaimer</h2>
<p>The Service is provided to You &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
<p>Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
<p>Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.</p>
<h2>Governing Law</h2>
<p>The laws of the Country, excluding its conflicts of law rules, shall govern these Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.</p>
<h2>Disputes Resolution</h2>
<p>If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.</p>
<h2>For European Union (EU) Users</h2>
<p>If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which You are resident.</p>
<h2>United States Legal Compliance</h2>
<p>You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a &quot;terrorist supporting&quot; country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
<h2>Severability and Waiver</h2>
<h3>Severability</h3>
<p>If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
<h3>Waiver</h3>
<p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute a waiver of any subsequent breach.</p>
<h2>Translation Interpretation</h2>
<p>These Terms and Conditions may have been translated if We have made them available to You on our Service.
You agree that the original English text shall prevail in the case of a dispute.</p>
<h2>Changes to These Terms and Conditions</h2>
<p>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.</p>
<p>By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the Service.</p>
<h2>Contact Us</h2>
<p>If you have any questions about these Terms and Conditions, You can contact us:</p>
<ul>
<li>
<p>By email: connect@tekverai.com</p>
</li>
<li>
<p>By phone: +12246589300</p>
</li>
</ul>
    `
  },
  cookies: {
    title: "Cookie Policy",
    icon: Globe,
    lastUpdated: "March 18, 2026",
    content: `
      <h1>Cookies Policy</h1>
<p>Last updated: March 16, 2026</p>
<p>This Cookies Policy explains what Cookies are and how We use them. You should read this policy so You can understand what type of cookies We use, or the information We collect using Cookies and how that information is used.</p>
<p>Cookies do not typically contain any information that personally identifies a user, but personal information that We store about You may be linked to the information stored in and obtained from Cookies. For further information on how We use, store and keep your personal data secure, see our Privacy Policy, if and when We make it available within the Website or on our website.</p>
<p>We do not store sensitive personal information, such as mailing addresses, account passwords, etc. in the Cookies We use.</p>
<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h3>Definitions</h3>
<p>For the purposes of this Cookies Policy:</p>
<ul>
<li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Cookies Policy) refers to Tekverai.com, 28 Geary St, Suite 650, San Francisco, CA 94108, United States .</li>
<li><strong>Cookies</strong> means small files that are placed on Your computer, mobile device or any other device by a website, containing details of your browsing history on that website among its many uses.</li>
<li><strong>Website</strong> refers to Tekverai.com, accessible from <a href="http://tekverai.com/" rel="external nofollow noopener" target="_blank">http://tekverai.com/</a>.</li>
<li><strong>You</strong> means the individual accessing or using the Website, or a company, or any legal entity on behalf of which such individual is accessing or using the Website, as applicable.</li>
</ul>
<h2>The use of the Cookies</h2>
<h3>Type of Cookies We Use</h3>
<p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.</p>
<p>Where required by law, We will request your consent before using Cookies that are not strictly necessary. Strictly necessary Cookies are used to provide the Website and cannot be switched off in our systems.</p>
<p>We use both session and persistent Cookies for the purposes set out below:</p>
<ul>
<li>
<p><strong>Necessary / Essential Cookies</strong></p>
<p>Type: Session Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
</li>
<li>
<p><strong>Functionality Cookies</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
</li>
</ul>
<h3>Your Choices Regarding Cookies</h3>
<p>If You prefer to avoid the use of Cookies on the Website, first You must disable the use of Cookies in your browser and then delete the Cookies saved in your browser associated with the Website. You may use this option for preventing the use of Cookies at any time.</p>
<p>If You do not accept Our Cookies, You may experience some inconvenience in your use of the Website and some features may not function properly.</p>
<p>If You'd like to delete Cookies or instruct your web browser to delete or refuse Cookies, please visit the help pages of your web browser.</p>
<ul>
<li>
<p>For the Chrome web browser, please visit this page from Google: <a href="https://support.google.com/accounts/answer/32050" rel="external nofollow noopener" target="_blank">https://support.google.com/accounts/answer/32050</a></p>
</li>
<li>
<p>For the Microsoft Edge browser, please visit this page from Microsoft: <a href="https://support.microsoft.com/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09" rel="external nofollow noopener" target="_blank">https://support.microsoft.com/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09</a></p>
</li>
<li>
<p>For the Firefox web browser, please visit this page from Mozilla: <a href="https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored" rel="external nofollow noopener" target="_blank">https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored</a></p>
</li>
<li>
<p>For the Safari web browser, please visit this page from Apple: <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" rel="external nofollow noopener" target="_blank">https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac</a></p>
</li>
</ul>
<p>For any other web browser, please visit your web browser's official web pages.</p>
<h3>Changes to this Cookies Policy</h3>
<p>We may update this Cookies Policy from time to time. The &quot;Last updated&quot; date at the top indicates when it was last revised.</p>
<h3>Contact Us</h3>
<p>If you have any questions about this Cookies Policy, You can contact us:</p>
<ul>
<li>
<p>By email: connect@tekverai.com</p>
</li>
<li>
<p>By phone: +12246589300</p>
</li>
</ul>
    `
  },
};

function LegalModal({ type, onClose }: { type: keyof typeof LEGAL_CONTENT; onClose: () => void }) {
  const data = LEGAL_CONTENT[type];
  const Icon = data.icon;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[2000] flex items-center justify-center p-4 md:p-6"
      style={{
        background: "radial-gradient(circle at 20% 20%, rgba(34,211,238,0.12), rgba(2,6,23,0.45) 45%, rgba(2,6,23,0.5) 100%)",
        backdropFilter: "blur(14px)",
      }}
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.9, opacity: 0, y: 20 }}
        transition={{ type: "spring", stiffness: 300, damping: 25 }}
        onClick={(e) => e.stopPropagation()}
        className="relative flex h-[88vh] w-full max-w-2xl flex-col overflow-hidden rounded-3xl border border-white/10 bg-[#0B0F1A] shadow-2xl md:h-[82vh]"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/5 bg-white/[0.02] px-8 py-6">
          <div className="flex items-center gap-4">
            <div className="flex size-10 items-center justify-center rounded-xl bg-cyan-500/10 text-cyan-400">
              <Icon size={20} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white">{data.title}</h3>
              <p className="text-xs text-slate-500">Last updated: {data.lastUpdated}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="flex size-10 items-center justify-center rounded-full text-slate-400 transition-colors hover:bg-white/5 hover:text-white"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="custom-scrollbar flex-1 min-h-0 overflow-y-auto px-6 py-6 md:px-8 md:py-8">
          <div
            className="legal-content max-w-none text-slate-300"
            dangerouslySetInnerHTML={{ __html: data.content }}
          />
        </div>

        {/* Footer */}
        <div className="border-t border-white/5 bg-white/[0.02] px-8 py-6 flex justify-end">
          <button
          title="Ok"
            onClick={onClose}
            className="rounded-xl bg-cyan-500 px-6 py-2.5 text-sm font-bold text-white transition-all hover:opacity-90 cursor-pointer"
          >
            UNDERSTOOD
          </button>
        </div>

        <style jsx global>{`
          .legal-content h2 {
            font-size: 1.35rem;
            line-height: 1.3;
            font-weight: 800;
            color: #ffffff;
            margin-top: 1.5rem;
            margin-bottom: 0.8rem;
          }
          .legal-content h3 {
            font-size: 1.05rem;
            line-height: 1.4;
            font-weight: 700;
            color: #f8fafc;
            margin-top: 1.2rem;
            margin-bottom: 0.6rem;
          }
          .legal-content h4 {
            font-size: 0.95rem;
            line-height: 1.45;
            font-weight: 700;
            color: #e2e8f0;
            margin-top: 1rem;
            margin-bottom: 0.45rem;
          }
          .legal-content p {
            font-size: 0.9rem;
            line-height: 1.72;
            color: #94a3b8;
            margin: 0.6rem 0;
          }
          .legal-content ul {
            margin: 0.65rem 0;
            padding-left: 1rem;
            list-style: disc;
          }
          .legal-content li {
            color: #94a3b8;
            margin: 0.3rem 0;
          }
          .legal-content strong {
            color: #e2e8f0;
            font-weight: 700;
          }
          .legal-content a {
            color: #22d3ee;
            text-decoration: underline;
            text-underline-offset: 2px;
          }
          .legal-content a:hover {
            color: #67e8f9;
          }
        `}</style>
      </motion.div>
    </motion.div>
  );
}

/* ─── Newsletter stub — wire to your backend here ───────────────────────── */
async function subscribeNewsletter(email: string, turnstileToken?: string): Promise<void> {
  const endpoint = process.env.NEXT_PUBLIC_FORMSPREE_NEWSLETTER_ENDPOINT;
  if (!endpoint) {
    throw new Error("Newsletter endpoint not found");
  }

  const payload: Record<string, string> = { email };
  if (turnstileToken) {
    payload["cf-turnstile-response"] = turnstileToken;
  }

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    throw new Error("Failed to subscribe");
  }
}

const NEWSLETTER_KEY = "tekverai_newsletter_subscribed";
const NEWSLETTER_TURNSTILE_TEMP_DISABLED = true;

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}

export default function Footer() {
  const [legalModal, setLegalModal] = useState<keyof typeof LEGAL_CONTENT | null>(null);

  // Newsletter state
  const [nlEmail, setNlEmail] = useState("");
  const [nlError, setNlError] = useState("");
  const [nlLoading, setNlLoading] = useState(false);
  const [nlSubscribed, setNlSubscribed] = useState(false);
  const [turnstileToken, setTurnstileToken] = useState<string | null>(null);
  const turnstileRef = useRef<TurnstileInstance>(null);

  useEffect(() => {
    if (typeof window !== "undefined" && localStorage.getItem(NEWSLETTER_KEY) === "1") {
      setNlSubscribed(true);
    }
  }, []);

  useEffect(() => {
    if (!legalModal) return;

    const prevBodyOverflow = document.body.style.overflow;
    const prevHtmlOverflow = document.documentElement.style.overflow;
    document.body.style.overflow = "hidden";
    document.documentElement.style.overflow = "hidden";

    return () => {
      document.body.style.overflow = prevBodyOverflow;
      document.documentElement.style.overflow = prevHtmlOverflow;
    };
  }, [legalModal]);

  async function handleSubscribe() {
    if (nlSubscribed || nlLoading) return;
    if (!nlEmail.trim()) { setNlError("Please enter your email address."); return; }
    if (!isValidEmail(nlEmail)) { setNlError("Please enter a valid email address."); return; }
    const newsletterTurnstileEnabled = !NEWSLETTER_TURNSTILE_TEMP_DISABLED;
    if (newsletterTurnstileEnabled && !turnstileToken) { setNlError("Please complete the security check."); return; }
    
    setNlError("");
    setNlLoading(true);
    try {
      await subscribeNewsletter(nlEmail.trim(), newsletterTurnstileEnabled ? (turnstileToken || undefined) : undefined);
      localStorage.setItem(NEWSLETTER_KEY, "1");
      setNlSubscribed(true);
      setTurnstileToken(null);
    } catch {
      setNlError("Something went wrong. Please try again.");
      if (newsletterTurnstileEnabled) {
        turnstileRef.current?.reset();
      }
    } finally {
      setNlLoading(false);
    }
  }

  return (
    <footer className="border-t border-[var(--color-border-subtle)] bg-[#020617] px-4 sm:px-6 md:px-12 pt-16 md:pt-20 lg:pt-24 xl:pt-32 pb-6 md:pb-8">
      <AnimatePresence>
        {legalModal && <LegalModal type={legalModal} onClose={() => setLegalModal(null)} />}
      </AnimatePresence>

      <div className="container-xl">
        <div className="mb-12 md:mb-16 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-5">
          {/* Brand */}
          <div className="lg:col-span-2">
            <Link href="/" className="mb-4 flex items-center gap-2 md:gap-2.5">
              <div className="flex size-8 md:size-[34px] items-center justify-center rounded-lg bg-[var(--color-accent)]">
                <ShieldCheck size={16} className="md:w-[18px] md:h-[18px] text-[#020617]" strokeWidth={2.5} />
              </div>
              <span className="text-base md:text-[17px] font-[700] text-[var(--color-text-primary)]">
                Tekver<span className="text-[var(--color-accent)]">AI</span>
              </span>
            </Link>
            <p className="mb-4 md:mb-6 max-w-[220px] text-sm md:text-[14px] leading-[1.6] text-[var(--color-text-secondary)]">
              AI-powered code and system verification for modern software teams.
            </p>
            {/* Social links */}
            <div className="flex gap-3">
              {[
                { icon: Twitter, href: "https://twitter.com/tekverai" },
                { icon: Facebook, href: "https://facebook.com/tekverai" },
                { icon: Youtube, href: "https://youtube.com/@tekverai" },
                { icon: PinterestIcon, href: "https://pinterest.com/tekverai" },
              ].map((social, i) => {
                const Icon = social.icon;
                return (
                  <a
                    key={i}
                    href={social.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group flex size-8 md:size-9 items-center justify-center rounded-lg border border-[var(--color-border-subtle)] bg-[var(--color-surface)] text-[var(--color-text-secondary)] transition-colors hover:border-[rgba(0,229,255,0.3)] hover:text-[var(--color-accent)]"
                  >
                    <Icon size={14} className="w-3.5 h-3.5 md:w-[15px] md:h-[15px]" />
                  </a>
                );
              })}
            </div>
          </div>

          {/* Link columns */}
          {Object.entries(footerLinks).map(([category, links]) => (
            <div key={category}>
              <h4 className="mb-3 md:mb-4 text-[11px] md:text-xs font-[700] uppercase tracking-[0.07em] text-[var(--color-text-primary)]">
                {category}
              </h4>
              <ul className="flex flex-col gap-2 md:gap-2.5">
                {links.map((link) => (
                  <li key={link.label}>
                    {"slug" in link ? (
                      <button
                        onClick={() => setLegalModal(link.slug as keyof typeof LEGAL_CONTENT)}
                        className="text-sm md:text-[14px] text-[var(--color-text-secondary)] transition-colors hover:text-[var(--color-text-primary)] cursor-pointer text-left"
                      >
                        {link.label}
                      </button>
                    ) : (
                      <Link
                        href={link.href}
                        className="text-sm md:text-[14px] text-[var(--color-text-secondary)] transition-colors hover:text-[var(--color-text-primary)]"
                      >
                        {link.label}
                      </Link>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Newsletter Section - Redesigned */}
        <div id="newsletter-section" className="mb-16 md:mb-20 lg:mb-24 px-0">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="group relative overflow-hidden rounded-2xl md:rounded-3xl border border-white/10 bg-gradient-to-br from-[#0B0F1A]/60 via-[#0B0F1A]/50 to-[#0B0F1A]/40 p-6 md:p-10 lg:p-12 backdrop-blur-md"
          >
            {/* Background Gradient Effects */}
            <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 via-transparent to-cyan-500/5 pointer-events-none" />
            <div className="absolute -top-20 -right-20 w-72 h-72 bg-gradient-to-br from-purple-500/10 to-cyan-500/10 blur-[120px] rounded-full pointer-events-none" />

            {/* Paper Plane Icon - Top Right */}
            <div className="absolute top-6 right-6 md:top-10 md:right-10 pointer-events-none">
              <motion.div
                animate={{
                  y: [0, -15, 0],
                  rotate: [-5, 0, -5],
                  x: [0, 10, 0]
                }}
                transition={{
                  duration: 5,
                  repeat: Infinity,
                  ease: "easeInOut"
                }}
                className="relative"
              >
                <svg width="80" height="80" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-16 h-16 md:w-24 md:h-24 lg:w-28 lg:h-28 text-cyan-400/50 drop-shadow-[0_0_30px_rgba(34,211,238,0.4)]">
                  <motion.path
                    initial={{ pathLength: 0, opacity: 0 }}
                    animate={{ pathLength: 1, opacity: 1 }}
                    transition={{ duration: 2, delay: 0.3 }}
                    d="M22 2L15 22L11 13L2 9L22 2Z"
                    fill="currentColor"
                    fillOpacity="0.3"
                    stroke="currentColor"
                    strokeWidth="1.2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                  <motion.path
                    initial={{ pathLength: 0, opacity: 0 }}
                    animate={{ pathLength: 1, opacity: 1 }}
                    transition={{ duration: 1.5, delay: 0.6 }}
                    d="M22 2L11 13"
                    stroke="currentColor"
                    strokeWidth="1.2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
                {/* Glow effect */}
                <div className="absolute inset-0 bg-cyan-500/20 blur-2xl rounded-full -z-10" />
              </motion.div>
            </div>

            {/* Content Container */}
            <div className="relative z-10 flex flex-col lg:flex-row items-start lg:items-center justify-between gap-8 lg:gap-12">
              {/* Left: Heading */}
              <div className="flex-1 max-w-lg">
                <h3 className="text-2xl md:text-3xl lg:text-4xl font-bold text-white leading-tight tracking-tight mb-1">
                  Essential industry updates.
                </h3>
                <p className="text-xl md:text-2xl lg:text-3xl font-bold text-slate-400 leading-tight tracking-tight">
                  Straight to your inbox.
                </p>
              </div>

              {/* Right: Email Input Form */}
              <div className="w-full lg:w-auto lg:min-w-[400px] xl:min-w-[480px]">
                <AnimatePresence mode="wait">
                  {nlSubscribed ? (
                    <motion.div
                      key="success"
                      initial={{ opacity: 0, scale: 0.92, y: 8 }}
                      animate={{ opacity: 1, scale: 1, y: 0 }}
                      exit={{ opacity: 0 }}
                      transition={{ type: "spring", stiffness: 340, damping: 26 }}
                      className="flex items-center gap-4 rounded-xl md:rounded-2xl border border-cyan-500/25 bg-cyan-500/8 px-5 py-4 shadow-lg"
                    >
                      <div className="flex size-10 flex-shrink-0 items-center justify-center rounded-full bg-cyan-500/15 border border-cyan-500/30">
                        <CheckCircle2 size={20} className="text-cyan-400" />
                      </div>
                      <div>
                        <p className="text-sm font-bold text-white">You&apos;re subscribed!</p>
                        <p className="text-xs text-slate-400 mt-0.5">Thanks for joining. We&apos;ll keep you updated.</p>
                      </div>
                    </motion.div>
                  ) : (
                    <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
                      {/* Turnstile Subscriber Protection */}
                      

                      <div
                        className={`relative flex items-stretch rounded-xl md:rounded-2xl border bg-[#020617]/60 backdrop-blur-sm overflow-hidden transition-all shadow-lg ${
                          nlError ? "border-red-500/40" : "border-white/10 focus-within:border-cyan-500/40"
                        }`}
                      >
                        <div className="flex items-center pl-3 md:pl-4 lg:pl-5 text-slate-500">
                          <Mail size={16} className="md:w-[18px] md:h-[18px] lg:w-5 lg:h-5" />
                        </div>
                        <input
                          id="newsletter-email"
                          type="email"
                          value={nlEmail}
                          onChange={e => { setNlEmail(e.target.value); if (nlError) setNlError(""); }}
                          onKeyDown={e => e.key === "Enter" && handleSubscribe()}
                          placeholder="Enter your business email"
                          disabled={nlLoading}
                          className="flex-1 min-w-0 bg-transparent border-none px-2 md:px-3 lg:px-4 py-3 md:py-3.5 lg:py-4 text-white placeholder:text-slate-600 focus:outline-none text-xs md:text-sm lg:text-base disabled:opacity-60"
                        />
                        <button
                          onClick={handleSubscribe}
                          disabled={nlLoading}
                          className="flex-shrink-0 flex items-center gap-2 px-4 md:px-6 lg:px-8 xl:px-10 py-3 md:py-3.5 lg:py-4 bg-gradient-to-r from-cyan-500 to-cyan-400 hover:from-cyan-400 hover:to-cyan-300 text-[#020617] font-bold transition-all shadow-[0_0_20px_rgba(34,211,238,0.3)] hover:shadow-[0_0_35px_rgba(34,211,238,0.5)] active:scale-[0.98] text-xs md:text-sm lg:text-base uppercase tracking-wide whitespace-nowrap disabled:opacity-70 disabled:cursor-not-allowed"
                        >
                          {nlLoading ? (
                            <><Loader2 size={15} className="animate-spin" /> Subscribing...</>
                          ) : "Subscribe"}
                        </button>
                      </div>
                      {nlError ? (
                        <motion.p
                          initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }}
                          className="mt-2 text-[11px] md:text-xs text-red-400 text-center lg:text-left"
                        >
                          {nlError}
                        </motion.p>
                      ) : (
                        <p className="mt-3 md:mt-4 text-[11px] md:text-xs text-slate-500 text-center lg:text-left">
                          Join 2,000+ developers. Opt-out at any time.
                        </p>
                      )}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Bottom row */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--color-border-subtle)] pt-6 md:pt-7">
          <p className="text-xs md:text-[13px] text-[var(--color-text-muted)]">
            &copy; {new Date().getFullYear()} TekverAI. All rights reserved.
          </p>

        </div>
      </div>
    </footer>
  );
}
